-- ============================================================
-- Sample data for ClothingStore_Final project
-- Compatible with MySQL 8.0+
-- Run this AFTER schema.sql to populate the database
-- ============================================================

USE clothingstore;

-- -----------------------------------------------------------
-- Products: 19 items across 5 categories
-- Image files must exist in webapp/product_img/
-- -----------------------------------------------------------
INSERT INTO `products` (`p_name`, `p_category`, `p_price`, `p_image`, `p_desc`) VALUES
('Sapphire Silk Saree', 'Saree', 2499.00, 'saree_1.jpeg', 'Luxurious sapphire blue silk saree with golden zari border.'),
('Morning Blossom Kurti', 'Kurti', 899.00, 'kurti_1.jpeg', 'Comfortable cotton kurti with floral embroidery.'),
('Velvet Party Lehenga', 'Lehenga', 4999.00, 'lehenga_1.jpeg', 'Rich velvet lehenga set with elegant mirror work.'),
('Emerald Anarkali', 'Suit', 1799.00, 'indo_western.jpeg', 'Premium emerald green anarkali with sequin accents.'),
('Churidar Set', 'Churidar', 1299.00, 'churidar_1.jpeg', 'Elegant churidar set for traditional occasions.'),
('Party Lehenga', 'Lehenga', 3999.00, 'lehenga_2.jpeg', 'Stunning party lehenga with intricate embroidery.'),
('Casual Kurti', 'Kurti', 699.00, 'kurti_2.jpeg', 'Simple and stylish kurti for daily wear.'),
('Indo Western Dress', 'Suit', 2199.00, 'indowestern_2.jpeg', 'Modern indo-western fusion dress.'),
('Bridal Lehenga', 'Lehenga', 7999.00, 'lehenga_3.jpeg', 'Exquisite bridal lehenga with heavy work.'),
('Orange Saree', 'Saree', 1899.00, 'orange.jpeg', 'Vibrant orange saree perfect for festivals.'),
('Purple Suit', 'Suit', 1599.00, 'puple_1.jpeg', 'Royal purple suit with delicate patterns.'),
('Designer Saree', 'Saree', 3499.00, 'saree_2.jpeg', 'Designer saree with contemporary design.'),
('Traditional Lehenga', 'Lehenga', 2999.00, 'lehenga_4.jpeg', 'Traditional lehenga for cultural events.'),
('Churidar Outfit', 'Churidar', 1099.00, 'churidar_2.jpeg', 'Comfortable churidar outfit for all day wear.'),
('Indo Western Style', 'Suit', 2399.00, 'indowestern_3.jpeg', 'Trendy indo-western style outfit.'),
('Silk Saree', 'Saree', 2799.00, 'saree_3.jpeg', 'Pure silk saree with rich texture.'),
('Festive Saree', 'Saree', 3199.00, 'Saree_4.jpeg', 'Festive saree with golden motifs.'),
('Elegant Saree', 'Saree', 2599.00, 'saree_6.jpeg', 'Elegant saree for special occasions.'),
('Classic Saree', 'Saree', 2299.00, 'saree_8.jpeg', 'Classic saree with timeless appeal.');

INSERT INTO `products` (`p_name`, `p_category`, `p_price`, `p_image`, `p_desc`) VALUES
('Luxury Lehenga L1', 'Lehenga', 3799.00, 'L1.jpeg', 'Elegant lehenga with sparkling embroidery.'),
('Luxury Lehenga L2', 'Lehenga', 3699.00, 'Rich lehenga with contrast blouse details.'),
('Silk Saree S1', 'Saree', 2199.00, 'S1.jpeg', 'Silk saree with classic drape and subtle shine.'),
('Silk Saree S1 Copy', 'Saree', 2199.00, 'S1 - Copy.jpeg', 'Duplicate-style saree image product entry.'),
('Magic Saree S2', 'Saree', 2299.00, 'S2.jpeg', 'Bright saree with festive decorative border.'),
('Magic Saree S2 Copy', 'Saree', 2299.00, 'S2 - Copy.jpeg', 'Duplicate-style saree image product entry.'),
('Chiffon Saree S3', 'Saree', 1999.00, 'S3.jpeg', 'Light chiffon saree with elegant print.'),
('Chiffon Saree S3 Copy', 'Saree', 1999.00, 'S3 - Copy.jpeg', 'Duplicate-style saree image product entry.'),
('Designer Saree S4', 'Saree', 2499.00, 'S4.jpeg', 'Designer saree with modern motifs.'),
('Designer Saree S4 Copy', 'Saree', 2499.00, 'S4 - Copy.jpeg', 'Duplicate-style saree image product entry.');

-- -----------------------------------------------------------
-- Admin user: needed to access the admin dashboard
-- The app checks if the login email matches the ADMIN_USER
-- environment variable (defaults to admin@example.com)
-- -----------------------------------------------------------
INSERT IGNORE INTO `user` (`userid`, `otp`) VALUES
('admin@example.com', NULL);

-- -----------------------------------------------------------
-- Test user: optional sample user for testing
-- OTP will be generated by the app on login
-- -----------------------------------------------------------
INSERT IGNORE INTO `user` (`userid`, `otp`) VALUES
('test.user@example.com', NULL);

-- -----------------------------------------------------------
-- Sample orders for the test user
-- Uses LAST_INSERT_ID() to link order_items safely
-- -----------------------------------------------------------
INSERT INTO `orders` (`user_id`, `total_amount`, `status`, `shipping_address`, `payment_method`) VALUES
('test.user@example.com', 2499.00, 'delivered', '123 Main St, City, State 12345', 'COD');

SET @order1_id = LAST_INSERT_ID();

INSERT INTO `order_items` (`o_id`, `p_id`, `p_name`, `p_price`, `p_image`, `size`, `quantity`, `subtotal`) VALUES
(@order1_id, 1, 'Sapphire Silk Saree', 2499.00, 'saree_1.jpeg', 'Free Size', 1, 2499.00);

INSERT INTO `orders` (`user_id`, `total_amount`, `status`, `shipping_address`, `payment_method`) VALUES
('test.user@example.com', 1799.00, 'shipped', '456 Oak Ave, Town, State 67890', 'Card');

SET @order2_id = LAST_INSERT_ID();

INSERT INTO `order_items` (`o_id`, `p_id`, `p_name`, `p_price`, `p_image`, `size`, `quantity`, `subtotal`) VALUES
(@order2_id, 4, 'Emerald Anarkali', 1799.00, 'indo_western.jpeg', 'M', 1, 1799.00);
